# Generated by Django 3.2.5 on 2022-06-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTransportPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.FloatField(verbose_name='Origin Latitude')),
                ('origin_lng', models.FloatField(verbose_name='Origin Longitude')),
                ('origin_name', models.CharField(max_length=50, verbose_name='Origin')),
                ('destination_lat', models.FloatField(verbose_name='Destination Latitude')),
                ('destination_lng', models.FloatField(verbose_name='Destination Longitude')),
                ('destination_name', models.CharField(max_length=50, verbose_name='Destination')),
                ('type_of_transport', models.CharField(choices=[('DRIVING', 'DRIVING'), ('WALKING', 'WALKING'), ('CYCLING', 'CYCLING')], max_length=30, verbose_name='Mode Of Transport')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserBookPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=5, verbose_name='Price (XAF)')),
                ('number_of_place', models.IntegerField()),
                ('payment_option', models.CharField(choices=[('CASH', 'CASH'), ('MOBILE MONEY', 'MOBILE MONEY'), ('ORANGE MONEY', 'ORANGE MONEY')], max_length=40)),
                ('accept', models.BooleanField(default=False)),
                ('place_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_place', models.CharField(max_length=250, verbose_name='Place search')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('ip_address', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user position',
                'verbose_name_plural': 'user positions',
            },
        ),
    ]
