# Generated by Django 3.2.5 on 2022-06-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookplace',
            name='number_of_place',
            field=models.IntegerField(default=1),
        ),
    ]
