# Generated by Django 3.2 on 2022-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_userbookplace_number_of_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookplace',
            name='accept',
        ),
        migrations.AddField(
            model_name='drivertransportpassenger',
            name='accept',
            field=models.CharField(choices=[('accept', 'accept'), ('refuse', 'refuse')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
