# Generated by Django 3.2 on 2022-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20220612_0549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivertransportpassenger',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='userbookplace',
            options={'ordering': ['-place_date']},
        ),
        migrations.AlterField(
            model_name='drivertransportpassenger',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
